### ISSUE TITLE
missing tags and releases

### ISSUE THREAD

**Issue by DanielRuf** [simonschaufi/foundation_grids#1]
It seems 1.2.0 is just here and not on the TER and the other releases are not tagged here.
It's the same on packagist.org.

**Comment by simonschaufi** [comment]
Hi Daniel!
Right, I didn't make a TER release yet as I have the feeling that this extension is not wide spread and I want to encourage users to use composer as it has so many advantages over the TER releases.

Sorry, I don't have the git history any more so I can't tag older releases.

Is there anything how I could help you?
